# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: arcflash.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'arcflash.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61rcflash.proto\x12\x08\x61rcflash\"g\n\tFlashBank\x12\x10\n\x08\x62\x61nk_ptr\x18\x01 \x01(\x05\x12\x10\n\x08\x62\x61nk_tag\x18\x02 \x01(\t\x12\x11\n\tbank_size\x18\x03 \x01(\x05\x12\x11\n\tbank_name\x18\x04 \x01(\t\x12\x10\n\x08\x63mos_tag\x18\x05 \x01(\t\"o\n\x0f\x46lashDescriptor\x12!\n\x04\x62\x61nk\x18\x01 \x03(\x0b\x32\x13.arcflash.FlashBank\x12\x11\n\thash_sha1\x18\x02 \x01(\t\x12\x12\n\nflash_size\x18\x03 \x01(\x05\x12\x12\n\nfree_space\x18\x04 \x01(\x05\"O\n\x04\x43MOS\x12\x10\n\x08\x63mos_tag\x18\x01 \x01(\t\x12\x10\n\x08\x62\x61nk_ptr\x18\x02 \x01(\x05\x12\x10\n\x08\x62\x61nk_tag\x18\x03 \x01(\t\x12\x11\n\tcmos_data\x18\x04 \x01(\x0c\"L\n\x0fSourceImageFile\x12%\n\x03rom\x18\x01 \x03(\x0b\x32\x18.arcflash.SourceRomImage\x12\x12\n\nbyte_order\x18\x02 \x01(\t\"\x93\x01\n\x0eSourceRomImage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0c\n\x04size\x18\x02 \x01(\x05\x12\x11\n\thash_sha1\x18\x03 \x01(\t\x12\x12\n\nlocal_path\x18\x04 \x03(\t\x12\x0b\n\x03tag\x18\x05 \x01(\t\x12\x0c\n\x04name\x18\x06 \x01(\t\x12\x10\n\x08\x63mos_tag\x18\x07 \x01(\t\x12\x11\n\tbank_size\x18\x08 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arcflash_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FLASHBANK']._serialized_start=28
  _globals['_FLASHBANK']._serialized_end=131
  _globals['_FLASHDESCRIPTOR']._serialized_start=133
  _globals['_FLASHDESCRIPTOR']._serialized_end=244
  _globals['_CMOS']._serialized_start=246
  _globals['_CMOS']._serialized_end=325
  _globals['_SOURCEIMAGEFILE']._serialized_start=327
  _globals['_SOURCEIMAGEFILE']._serialized_end=403
  _globals['_SOURCEROMIMAGE']._serialized_start=406
  _globals['_SOURCEROMIMAGE']._serialized_end=553
# @@protoc_insertion_point(module_scope)
