name: Test CPLD

on: push

jobs:
  test:
    name: Test CPLD
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get -y install iverilog
          python3 -m pip install cocotb

      - name: Test
        run: |
          make -C cpld test
