name: Build firmware and boot menu

on: push

jobs:
  build_firmware_bootmenu:
    name: Build firmware and boot menu
    runs-on: ubuntu-latest
    container: ghcr.io/myelin/arcflash-builder@main

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build packages
        run: |
          cd /github/workspace
          find .
          make release

      - uses: actions/upload-artifact@v4
        with:
          name: firmware-bootmenu
          path: |
            python_lib/arcflash/bootmenu.bin
            python_lib/arcflash/firmware.bin
