name: Test host_mcu_comms

on: push

jobs:
  test:
    name: Test host_mcu_comms
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: |
          make -C host_mcu_comms test
